#!/bin/bash
preparar() {
  awk '{print "N" OFS $0}' "$@"
}

datos() {
  bin/inputs
}

prefijo() {
  sed -r \
    -e 's#^data/#results/001/#g' \
    -e 's#/001/#/002/#g' \
    -e 's#\.txt$##g'
}

genes() {
   ARCHIVO="$1"
   bin/genes "$ARCHIVO"
}

revisar_redes() {
  bin/inputs \
  | bin/input2check \
  | xargs -l mk
}

adj_from_txt() {
    FILE="$1"
    join \
	<(echo "$FILE" | prefijo | preparar) \
	<(bin/genes "$FILE" | cat -n | preparar) \
    | awk '{print $2 "." $3 "." $4 ".adj"}'
}
